import { Archive, CalendarBlank, CaretLeft, CaretRight, ChatText, CloudArrowDown, DownloadSimple, Package, PencilSimple, Plus, SignOut, SquaresFour, Trash, UploadSimple, X } from '@phosphor-icons/react'
import { useEffect, useMemo, useState } from 'react'
import { archiveCatalogItem, getCatalogPage, getTaxonomies, removeCatalogItem, restoreCatalogItem, saveCatalogItem, VEHICLE_TYPES } from '../lib/catalog'
import { firebaseConfigured } from '../lib/firebase'
import { login, logout, startImport, watchAdmin, watchBihrSyncJobs, watchImportJobs } from '../lib/admin'
import { updateRequest, watchRequests } from '../lib/requests'

const emptyItem = { reference: '', description: '', price: '', discount: 0, vehicleType: 'unclassified', categoryId: '', subcategoryId: '', status: 'active', imageUrl: '' }
const money = new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR' })

export function AdminPage({ navigate }) {
  const [session, setSession] = useState({ loading: true, user: null, isAdmin: false })
  useEffect(() => {
    if (!firebaseConfigured) { setSession({ loading: false, user: null, isAdmin: false }); return undefined }
    return watchAdmin((next) => setSession({ ...next, loading: false }))
  }, [])
  if (!firebaseConfigured) return <AdminNotice title="Firebase aún no está configurado" text="Completa las variables VITE_FIREBASE_* para habilitar el panel de administración." />
  if (session.loading) return <AdminNotice title="Comprobando acceso…" text="" />
  if (!session.user) return <Login />
  if (!session.isAdmin) return <AdminNotice title="Acceso no autorizado" text={`El usuario ${session.user.email} no tiene rol de administrador.`} onLogout={logout} />
  return <AdminDashboard navigate={navigate} user={session.user} />
}

function Login() {
  const [error, setError] = useState(''); const [pending, setPending] = useState(false)
  async function submit(event) { event.preventDefault(); setPending(true); setError(''); const form = new FormData(event.currentTarget); try { await login(form.get('email'), form.get('password')) } catch { setError('No se ha podido iniciar sesión. Revisa tus credenciales.') } finally { setPending(false) } }
  return <main className="admin-login"><form onSubmit={submit}><span className="admin-brand">VICTIKER</span><h1>Administración</h1><p>Accede para gestionar el catálogo.</p><label>Email<input required name="email" type="email" autoComplete="email" /></label><label>Contraseña<input required name="password" type="password" autoComplete="current-password" /></label>{error && <p className="form-error">{error}</p>}<button className="button" disabled={pending}>{pending ? 'Entrando…' : 'Entrar'}</button></form></main>
}

function AdminNotice({ title, text, onLogout }) { return <main className="admin-login"><div><span className="admin-brand">VICTIKER</span><h1>{title}</h1>{text && <p>{text}</p>}{onLogout && <button className="button button--dark" onClick={onLogout}>Cerrar sesión</button>}</div></main> }

function AdminDashboard({ navigate, user }) {
  const [section, setSection] = useState('catalog'); const [items, setItems] = useState([]); const [cursor, setCursor] = useState(null); const [history, setHistory] = useState([])
  const [filters, setFilters] = useState({ term: '', vehicleType: 'all', status: 'active' }); const [loading, setLoading] = useState(true); const [editor, setEditor] = useState(null); const [taxonomies, setTaxonomies] = useState([]); const [message, setMessage] = useState(''); const [partsRequests, setPartsRequests] = useState([]); const [appointmentRequests, setAppointmentRequests] = useState([])
  const categories = useMemo(() => taxonomies.filter((entry) => !entry.parentId && entry.active), [taxonomies])
  async function load(nextCursor = null, reset = false) { setLoading(true); try { const result = await getCatalogPage({ ...filters, cursor: nextCursor, admin: { status: filters.status } }); setItems(result.items); setCursor(result.nextCursor); if (reset) setHistory([]) } catch (error) { setMessage(error.message) } finally { setLoading(false) } }
  async function loadTaxonomies() { try { setTaxonomies(await getTaxonomies()) } catch (error) { setMessage(error.message) } }
  useEffect(() => { load(null, true); loadTaxonomies() }, [filters.term, filters.vehicleType, filters.status])
  useEffect(() => { const stopParts = watchRequests('parts', (next, error) => { if (error) setMessage(error.message); setPartsRequests(next) }); const stopAppointments = watchRequests('appointment', (next, error) => { if (error) setMessage(error.message); setAppointmentRequests(next) }); return () => { stopParts(); stopAppointments() } }, [])
  async function save(item) { if (item.source === 'bihr') { setMessage('Las referencias de Bihr se actualizan automáticamente y no se pueden editar.'); return } try { await saveCatalogItem(item.id, item, user.uid); setEditor(null); setMessage('Pieza guardada.'); load(null, true) } catch (error) { setMessage(error.message) } }
  async function action(type, item) { const label = type === 'delete' ? 'borrar definitivamente' : type === 'archive' ? 'archivar' : 'restaurar'; if (!window.confirm(`¿Quieres ${label} “${item.reference}”?`)) return; try { if (type === 'delete') await removeCatalogItem(item.id); if (type === 'archive') await archiveCatalogItem(item.id, user.uid); if (type === 'restore') await restoreCatalogItem(item.id, user.uid); setMessage('Cambio guardado.'); load(null, true) } catch (error) { setMessage(error.message) } }
  return <main className="admin-shell"><aside className="admin-sidebar"><button className="admin-brand" onClick={() => navigate('/')}><img src="/assets/victiker-logo-header.png" alt="Victiker" /></button><nav><button className={section === 'catalog' ? 'is-active' : ''} onClick={() => setSection('catalog')}><SquaresFour size={17} weight="duotone" /><span>Catálogo</span></button><button className={section === 'parts' ? 'is-active' : ''} onClick={() => setSection('parts')}><Package size={17} weight="duotone" /><span>Pedidos</span></button><button className={section === 'appointments' ? 'is-active' : ''} onClick={() => setSection('appointments')}><CalendarBlank size={17} weight="duotone" /><span>Citas</span></button><button className={section === 'imports' ? 'is-active' : ''} onClick={() => setSection('imports')}><UploadSimple size={17} weight="duotone" /><span>Importaciones</span></button></nav><button className="admin-signout" onClick={logout}><SignOut size={17} /> <span>Cerrar sesión</span></button></aside><section className="admin-content">
    {message && <div className="admin-message" role="status">{message}<button onClick={() => setMessage('')}><X size={16} /></button></div>}
    {section === 'catalog' && <CatalogAdmin items={items} filters={filters} setFilters={setFilters} loading={loading} cursor={cursor} history={history} categories={categories} onEdit={setEditor} onNext={() => { setHistory([...history, { items, cursor }]); load(cursor) }} onPrevious={() => { const pages = [...history]; const previous = pages.pop(); setHistory(pages); setItems(previous.items); setCursor(previous.cursor) }} onAction={action} onAdd={() => setEditor(emptyItem)} />}
    {section === 'parts' && <RequestsAdmin type="parts" requests={partsRequests} setMessage={setMessage} />}
    {section === 'appointments' && <RequestsAdmin type="appointment" requests={appointmentRequests} setMessage={setMessage} />}
    {section === 'imports' && <Imports user={user} setMessage={setMessage} />}
  </section>{editor && <Editor item={editor} categories={categories} taxonomies={taxonomies} onClose={() => setEditor(null)} onSave={save} />}</main>
}

function RequestsAdmin({ type, requests, setMessage }) {
  const [selected, setSelected] = useState(null)
  async function save(request, changes) { try { await updateRequest(request.id, changes); setSelected({ ...request, ...changes }); setMessage('Solicitud actualizada.') } catch (error) { setMessage(error.message) } }
  const isParts = type === 'parts'
  return <><header className="admin-header"><div><h1>{isParts ? 'Pedidos' : 'Citas'}</h1><p>{isParts ? 'Gestiona las solicitudes de repuestos recibidas desde la web.' : 'Gestiona las solicitudes de cita recibidas desde la web.'}</p></div></header><div className="request-workspace"><div className="request-list">{requests.length === 0 ? <p className="admin-loading">No hay {isParts ? 'pedidos' : 'citas'} todavía.</p> : requests.map((request) => <button key={request.id} className={selected?.id === request.id ? 'is-selected' : ''} onClick={() => setSelected(request)}><strong>{request.name}</strong><span>{isParts ? `${request.items?.length || 0} referencias` : request.need}</span><small>{formatJobDate(request.createdAt)} · {request.status === 'new' ? 'Nueva' : request.status}</small></button>)}</div>{selected ? <RequestDetail request={selected} onSave={save} /> : <div className="request-detail request-detail--empty"><ChatText size={36} /><p>Selecciona una solicitud para ver sus datos y añadir notas internas.</p></div>}</div></>
}

function RequestDetail({ request, onSave }) {
  const [notes, setNotes] = useState(request.notes || ''); const [status, setStatus] = useState(request.status || 'new')
  useEffect(() => { setNotes(request.notes || ''); setStatus(request.status || 'new') }, [request.id, request.notes, request.status])
  const isParts = request.type === 'parts'
  return <article className="request-detail"><header><div><span className="request-detail__eyebrow">{isParts ? 'Solicitud de repuestos' : 'Solicitud de cita'}</span><h2>{request.name}</h2></div><span className={`catalog-status catalog-status--${request.status}`}>{request.status === 'new' ? 'Nueva' : request.status}</span></header><dl><dt>Teléfono</dt><dd>{request.phone}</dd>{isParts ? <><dt>Vehículo</dt><dd>{request.vehicle || 'No especificado'}</dd><dt>Piezas</dt><dd>{request.items?.map((item) => `${item.description || item.title} · ${item.reference} × ${item.quantity}`).join('\n') || '—'}</dd></> : <><dt>Necesidad</dt><dd>{request.need}</dd><dt>Detalles</dt><dd>{request.details || '—'}</dd></>}</dl><label className="request-notes">Notas internas<textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Escribe aquí el seguimiento privado…" rows="7" /></label><footer><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="new">Nueva</option><option value="in_progress">En curso</option><option value="completed">Completada</option><option value="cancelled">Cancelada</option></select><button className="button" onClick={() => onSave(request, { notes, status })}>Guardar cambios</button></footer></article>
}

function CatalogAdmin({ items, filters, setFilters, loading, cursor, history, categories, onEdit, onNext, onPrevious, onAction, onAdd }) { return <><header className="admin-header"><div><h1>Catálogo</h1><p>Consulta, edita y gestiona las referencias.</p></div><button className="button" onClick={onAdd}><Plus size={18} /> Añadir pieza</button></header><div className="admin-toolbar"><input value={filters.term} onChange={(event) => setFilters({ ...filters, term: event.target.value })} placeholder="Buscar por referencia o descripción" /><select value={filters.vehicleType} onChange={(event) => setFilters({ ...filters, vehicleType: event.target.value })}><option value="all">Todos los vehículos</option>{VEHICLE_TYPES.map((type) => <option key={type.id} value={type.id}>{type.label}</option>)}</select><select value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })}><option value="active">Activas</option><option value="archived">Archivadas</option></select></div><div className="admin-table"><div className="admin-table__head"><span>Referencia</span><span>Descripción</span><span>Clasificación</span><span>Precio</span><span>Estado</span><span /></div>{loading ? <p className="admin-loading">Cargando referencias…</p> : items.map((item) => <article key={item.id}><span>{item.reference}</span><strong>{item.description}</strong><span>{item.vehicleType} · {categories.find((entry) => entry.id === item.categoryId)?.name || 'Sin categoría'}{item.source === 'bihr' ? ' · Bihr' : ''}</span><span>{money.format(item.price)}</span><span className={`catalog-status catalog-status--${item.status}`}>{item.status === 'active' ? 'Activa' : 'Archivada'}</span><div>{item.source !== 'bihr' && <button onClick={() => onEdit(item)} aria-label="Editar"><PencilSimple size={18} /></button>}{item.status === 'active' ? <button onClick={() => onAction('archive', item)} aria-label="Archivar"><Archive size={18} /></button> : <button onClick={() => onAction('restore', item)}>Restaurar</button>}<button onClick={() => onAction('delete', item)} aria-label="Borrar definitivamente"><Trash size={18} /></button></div></article>)}</div><nav className="pagination"><button disabled={!history.length} onClick={onPrevious}><CaretLeft size={18} /></button><span>Página {history.length + 1}</span><button disabled={!cursor} onClick={onNext}><CaretRight size={18} /></button></nav></> }

function Editor({ item, categories, taxonomies, onClose, onSave }) { const [value, setValue] = useState(item); const subcategories = taxonomies.filter((entry) => entry.parentId === value.categoryId && entry.active); const update = (key, next) => setValue({ ...value, [key]: next, ...(key === 'categoryId' ? { subcategoryId: '' } : {}) }); return <aside className="admin-editor"><header><h2>{item.id ? 'Editar pieza' : 'Añadir pieza'}</h2><button onClick={onClose}><X size={22} /></button></header><label>Referencia *<input value={value.reference} onChange={(event) => update('reference', event.target.value)} /></label><label>Descripción *<textarea value={value.description} onChange={(event) => update('description', event.target.value)} /></label><label>Tipo de vehículo<select value={value.vehicleType} onChange={(event) => update('vehicleType', event.target.value)}>{VEHICLE_TYPES.map((type) => <option key={type.id} value={type.id}>{type.label}</option>)}</select></label><label>Categoría<select value={value.categoryId || ''} onChange={(event) => update('categoryId', event.target.value)}><option value="">Sin categoría</option>{categories.filter((entry) => entry.vehicleType === value.vehicleType || entry.vehicleType === 'all').map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label><label>Subcategoría<select value={value.subcategoryId || ''} onChange={(event) => update('subcategoryId', event.target.value)}><option value="">Sin subcategoría</option>{subcategories.map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label><label>Precio (€) *<input type="number" min="0" step="0.01" value={value.price} onChange={(event) => update('price', event.target.value)} /></label><label>Descuento (%)<input type="number" min="0" max="100" value={value.discount} onChange={(event) => update('discount', event.target.value)} /></label><label>URL de imagen<input type="url" value={value.imageUrl || ''} onChange={(event) => update('imageUrl', event.target.value)} placeholder="https://…" /></label>{value.imageUrl && <img className="admin-editor__image" src={value.imageUrl} alt="Vista previa de la pieza" referrerPolicy="no-referrer" />}<footer><button className="button button--ghost" onClick={onClose}>Cancelar</button><button className="button" onClick={() => onSave(value)}>Guardar cambios</button></footer></aside> }

function formatJobDate(value) { try { return value?.toDate().toLocaleString('es-ES', { dateStyle: 'short', timeStyle: 'short' }) || '—' } catch { return '—' } }
const BIHR_ACTIVE_WINDOW_MS = 35 * 60 * 1000
function isBihrJobActive(job, now = Date.now()) { const startedAt = job?.startedAt?.toMillis?.() || 0; return ['downloading', 'processing'].includes(job?.status) && startedAt > now - BIHR_ACTIVE_WINDOW_MS }
function jobStatus(job, now = Date.now()) { if (['downloading', 'processing'].includes(job?.status) && !isBihrJobActive(job, now)) return 'Interrumpida'; return ({ awaiting_upload: 'Esperando archivo', downloading: 'Descargando', processing: 'Procesando', completed: 'Completada', failed: 'Error' })[job?.status] || job?.status }

function Imports({ setMessage }) {
  const [file, setFile] = useState(null); const [pending, setPending] = useState(false); const [progress, setProgress] = useState(0); const [jobs, setJobs] = useState([]); const [bihrJobs, setBihrJobs] = useState([]); const [now, setNow] = useState(Date.now())
  useEffect(() => watchImportJobs(setJobs), []); useEffect(() => watchBihrSyncJobs(setBihrJobs), [])
  useEffect(() => { if (!['downloading', 'processing'].includes(bihrJobs[0]?.status)) return undefined; const timer = window.setInterval(() => setNow(Date.now()), 60_000); return () => window.clearInterval(timer) }, [bihrJobs])
  async function submit(event) { event.preventDefault(); if (!file) return; setPending(true); try { const result = await startImport(file, setProgress); setMessage(`Archivo subido (${result.progress} %). El procesamiento continuará en segundo plano.`) } catch (error) { setMessage(error.message) } finally { setPending(false) } }
  const lastBihrJob = bihrJobs[0]
  return <><header className="admin-header"><div><h1>Importaciones</h1><p>Dos fuentes separadas para mantener cada catálogo bajo control.</p></div></header><div className="imports-sections"><section className="import-card import-card--moto"><div className="import-card__header"><div className="import-card__icon"><CloudArrowDown size={25} weight="duotone" /></div><div><span className="import-card__eyebrow">Motos</span><h2>Catálogo Bihr</h2><p>Sincronización automática cada lunes a las 05:30. Compara el catálogo completo y actualiza únicamente las referencias nuevas o modificadas.</p></div></div>{lastBihrJob && <div className="bihr-sync-status"><span><small>Última ejecución</small><strong>{formatJobDate(lastBihrJob.createdAt)}</strong></span><span><small>Estado</small><strong>{jobStatus(lastBihrJob, now)}</strong></span><span><small>Catálogo</small><strong>{lastBihrJob.processed || lastBihrJob.downloaded || 0} piezas</strong></span><span><small>Nuevas / modificadas</small><strong>{lastBihrJob.new || 0} / {lastBihrJob.modified || 0}</strong></span><span><small>Sin cambios</small><strong>{lastBihrJob.unchanged || 0}</strong></span><span><small>Archivadas</small><strong>{lastBihrJob.archived || 0}</strong></span>{lastBihrJob.writesTotal > 0 && <div className="bihr-sync-progress"><progress max={lastBihrJob.writesTotal} value={lastBihrJob.writes || 0} /><small>{lastBihrJob.writes || 0} de {lastBihrJob.writesTotal} cambios aplicados</small></div>}{lastBihrJob.error && <p>{lastBihrJob.error}</p>}</div>}</section><section className="import-card import-card--boat"><div className="import-card__header"><div className="import-card__icon"><UploadSimple size={25} weight="duotone" /></div><div><span className="import-card__eyebrow">Barco</span><h2>Importar CSV</h2><p>La referencia es obligatoria. Las categorías y subcategorías del archivo se crean automáticamente en el catálogo.</p></div></div><form className="boat-import-form" onSubmit={submit}><label>Archivo CSV<input type="file" accept=".csv,text/csv" onChange={(event) => setFile(event.target.files[0] || null)} /></label><div className="import-card__actions"><a className="button button--secondary" href="/muestra-catalogo-barco.csv" download><DownloadSimple size={18} />Descargar CSV de muestra</a><button className="button" disabled={!file || pending}>{pending ? `Subiendo ${progress} %…` : 'Subir e importar'}</button></div></form>{jobs.length > 0 && <div className="import-jobs">{jobs.map((job) => <article key={job.id}><strong>{job.fileName}</strong><span>{jobStatus(job)}</span><small>{job.processed || 0} procesadas · {job.created || 0} nuevas · {job.updated || 0} actualizadas · {job.rejected || 0} rechazadas</small></article>)}</div>}</section></div></>
}
