import { Archive, CaretLeft, CaretRight, DownloadSimple, PencilSimple, Plus, SignOut, SquaresFour, Tag, UploadSimple, X } from '@phosphor-icons/react'
import { useEffect, useMemo, useState } from 'react'
import { archiveCatalogItem, getCatalogPage, getTaxonomies, removeCatalogItem, restoreCatalogItem, saveCatalogItem, saveTaxonomy, setTaxonomyActive, VEHICLE_TYPES } from '../lib/catalog'
import { firebaseConfigured } from '../lib/firebase'
import { login, logout, startImport, watchAdmin, watchImportJobs } from '../lib/admin'

const emptyItem = { reference: '', description: '', price: '', discount: 0, vehicleType: 'unclassified', categoryId: '', subcategoryId: '', status: 'active' }
const money = new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR' })

export function AdminPage({ navigate }) {
  const [session, setSession] = useState({ loading: true, user: null, isAdmin: false })
  useEffect(() => {
    if (!firebaseConfigured) { setSession({ loading: false, user: null, isAdmin: false }); return undefined }
    return watchAdmin((next) => setSession({ ...next, loading: false }))
  }, [])
  if (!firebaseConfigured) return <AdminNotice title="Firebase aún no está configurado" text="Completa las variables VITE_FIREBASE_* para habilitar el panel de administración." />
  if (session.loading) return <AdminNotice title="Comprobando acceso…" text="" />
  if (!session.user) return <Login />
  if (!session.isAdmin) return <AdminNotice title="Acceso no autorizado" text={`El usuario ${session.user.email} no tiene rol de administrador.`} onLogout={logout} />
  return <AdminDashboard navigate={navigate} user={session.user} />
}

function Login() {
  const [error, setError] = useState(''); const [pending, setPending] = useState(false)
  async function submit(event) { event.preventDefault(); setPending(true); setError(''); const form = new FormData(event.currentTarget); try { await login(form.get('email'), form.get('password')) } catch { setError('No se ha podido iniciar sesión. Revisa tus credenciales.') } finally { setPending(false) } }
  return <main className="admin-login"><form onSubmit={submit}><span className="admin-brand">VICTIKER</span><h1>Administración</h1><p>Accede para gestionar el catálogo.</p><label>Email<input required name="email" type="email" autoComplete="email" /></label><label>Contraseña<input required name="password" type="password" autoComplete="current-password" /></label>{error && <p className="form-error">{error}</p>}<button className="button" disabled={pending}>{pending ? 'Entrando…' : 'Entrar'}</button></form></main>
}

function AdminNotice({ title, text, onLogout }) { return <main className="admin-login"><div><span className="admin-brand">VICTIKER</span><h1>{title}</h1>{text && <p>{text}</p>}{onLogout && <button className="button button--dark" onClick={onLogout}>Cerrar sesión</button>}</div></main> }

function AdminDashboard({ navigate, user }) {
  const [section, setSection] = useState('catalog'); const [items, setItems] = useState([]); const [cursor, setCursor] = useState(null); const [history, setHistory] = useState([])
  const [filters, setFilters] = useState({ term: '', vehicleType: 'all', status: 'active' }); const [loading, setLoading] = useState(true); const [editor, setEditor] = useState(null); const [taxonomies, setTaxonomies] = useState([]); const [message, setMessage] = useState('')
  const categories = useMemo(() => taxonomies.filter((entry) => !entry.parentId && entry.active), [taxonomies])
  async function load(nextCursor = null, reset = false) { setLoading(true); try { const result = await getCatalogPage({ ...filters, cursor: nextCursor, admin: { status: filters.status } }); setItems(result.items); setCursor(result.nextCursor); if (reset) setHistory([]) } catch (error) { setMessage(error.message) } finally { setLoading(false) } }
  async function loadTaxonomies() { try { setTaxonomies(await getTaxonomies()) } catch (error) { setMessage(error.message) } }
  useEffect(() => { load(null, true); loadTaxonomies() }, [filters.term, filters.vehicleType, filters.status])
  async function save(item) { try { await saveCatalogItem(item.id, item, user.uid); setEditor(null); setMessage('Pieza guardada.'); load(null, true) } catch (error) { setMessage(error.message) } }
  async function action(type, item) { const label = type === 'delete' ? 'borrar definitivamente' : type === 'archive' ? 'archivar' : 'restaurar'; if (!window.confirm(`¿Quieres ${label} “${item.reference}”?`)) return; try { if (type === 'delete') await removeCatalogItem(item.id); if (type === 'archive') await archiveCatalogItem(item.id, user.uid); if (type === 'restore') await restoreCatalogItem(item.id, user.uid); setMessage('Cambio guardado.'); load(null, true) } catch (error) { setMessage(error.message) } }
  return <main className="admin-shell"><aside className="admin-sidebar"><button className="admin-brand" onClick={() => navigate('/')}><span>VICTIKER</span><small>ADMIN CONSOLE</small></button><div className="admin-nav-label">Workspace</div><nav><button className={section === 'catalog' ? 'is-active' : ''} onClick={() => setSection('catalog')}><SquaresFour size={17} weight="duotone" /><span>Catálogo</span></button><button className={section === 'taxonomy' ? 'is-active' : ''} onClick={() => setSection('taxonomy')}><Tag size={17} weight="duotone" /><span>Taxonomías</span></button><button className={section === 'imports' ? 'is-active' : ''} onClick={() => setSection('imports')}><UploadSimple size={17} weight="duotone" /><span>Importaciones</span></button></nav><button className="admin-signout" onClick={logout}><SignOut size={17} /> <span>Cerrar sesión</span></button></aside><section className="admin-content">
    {message && <div className="admin-message" role="status">{message}<button onClick={() => setMessage('')}><X size={16} /></button></div>}
    {section === 'catalog' && <CatalogAdmin items={items} filters={filters} setFilters={setFilters} loading={loading} cursor={cursor} history={history} categories={categories} onEdit={setEditor} onNext={() => { setHistory([...history, { items, cursor }]); load(cursor) }} onPrevious={() => { const pages = [...history]; const previous = pages.pop(); setHistory(pages); setItems(previous.items); setCursor(previous.cursor) }} onAction={action} onAdd={() => setEditor(emptyItem)} />}
    {section === 'taxonomy' && <TaxonomyAdmin taxonomies={taxonomies} onSave={async (value) => { await saveTaxonomy(null, value, user.uid); await loadTaxonomies() }} onToggle={async (entry) => { await setTaxonomyActive(entry.id, !entry.active, user.uid); await loadTaxonomies() }} />}
    {section === 'imports' && <Imports user={user} setMessage={setMessage} />}
  </section>{editor && <Editor item={editor} categories={categories} taxonomies={taxonomies} onClose={() => setEditor(null)} onSave={save} />}</main>
}

function CatalogAdmin({ items, filters, setFilters, loading, cursor, history, categories, onEdit, onNext, onPrevious, onAction, onAdd }) { return <><header className="admin-header"><div><h1>Catálogo</h1><p>Consulta, edita y gestiona las referencias.</p></div><button className="button" onClick={onAdd}><Plus size={18} /> Añadir pieza</button></header><div className="admin-toolbar"><input value={filters.term} onChange={(event) => setFilters({ ...filters, term: event.target.value })} placeholder="Buscar por referencia o descripción" /><select value={filters.vehicleType} onChange={(event) => setFilters({ ...filters, vehicleType: event.target.value })}><option value="all">Todos los vehículos</option>{VEHICLE_TYPES.map((type) => <option key={type.id} value={type.id}>{type.label}</option>)}</select><select value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })}><option value="active">Activas</option><option value="archived">Archivadas</option></select></div><div className="admin-table"><div className="admin-table__head"><span>Referencia</span><span>Descripción</span><span>Clasificación</span><span>Precio</span><span>Estado</span><span /></div>{loading ? <p className="admin-loading">Cargando referencias…</p> : items.map((item) => <article key={item.id}><span>{item.reference}</span><strong>{item.description}</strong><span>{item.vehicleType} · {categories.find((entry) => entry.id === item.categoryId)?.name || 'Sin categoría'}</span><span>{money.format(item.price)}</span><span className={`catalog-status catalog-status--${item.status}`}>{item.status === 'active' ? 'Activa' : 'Archivada'}</span><div><button onClick={() => onEdit(item)} aria-label="Editar"><PencilSimple size={18} /></button>{item.status === 'active' ? <button onClick={() => onAction('archive', item)} aria-label="Archivar"><Archive size={18} /></button> : <button onClick={() => onAction('restore', item)}>Restaurar</button>}<button onClick={() => onAction('delete', item)} aria-label="Borrar definitivamente"><Trash size={18} /></button></div></article>)}</div><nav className="pagination"><button disabled={!history.length} onClick={onPrevious}><CaretLeft size={18} /></button><span>Página {history.length + 1}</span><button disabled={!cursor} onClick={onNext}><CaretRight size={18} /></button></nav></> }

function Editor({ item, categories, taxonomies, onClose, onSave }) { const [value, setValue] = useState(item); const subcategories = taxonomies.filter((entry) => entry.parentId === value.categoryId && entry.active); const update = (key, next) => setValue({ ...value, [key]: next, ...(key === 'categoryId' ? { subcategoryId: '' } : {}) }); return <aside className="admin-editor"><header><h2>{item.id ? 'Editar pieza' : 'Añadir pieza'}</h2><button onClick={onClose}><X size={22} /></button></header><label>Referencia *<input value={value.reference} onChange={(event) => update('reference', event.target.value)} /></label><label>Descripción *<textarea value={value.description} onChange={(event) => update('description', event.target.value)} /></label><label>Tipo de vehículo<select value={value.vehicleType} onChange={(event) => update('vehicleType', event.target.value)}>{VEHICLE_TYPES.map((type) => <option key={type.id} value={type.id}>{type.label}</option>)}</select></label><label>Categoría<select value={value.categoryId || ''} onChange={(event) => update('categoryId', event.target.value)}><option value="">Sin categoría</option>{categories.filter((entry) => entry.vehicleType === value.vehicleType || entry.vehicleType === 'all').map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label><label>Subcategoría<select value={value.subcategoryId || ''} onChange={(event) => update('subcategoryId', event.target.value)}><option value="">Sin subcategoría</option>{subcategories.map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label><label>Precio (€) *<input type="number" min="0" step="0.01" value={value.price} onChange={(event) => update('price', event.target.value)} /></label><label>Descuento (%)<input type="number" min="0" max="100" value={value.discount} onChange={(event) => update('discount', event.target.value)} /></label><footer><button className="button button--ghost" onClick={onClose}>Cancelar</button><button className="button" onClick={() => onSave(value)}>Guardar cambios</button></footer></aside> }

function TaxonomyAdmin({ taxonomies, onSave, onToggle }) { const [value, setValue] = useState({ name: '', vehicleType: 'moto', parentId: '' }); return <><header className="admin-header"><div><h1>Taxonomías</h1><p>Define las categorías y subcategorías del catálogo.</p></div></header><form className="taxonomy-form" onSubmit={(event) => { event.preventDefault(); onSave(value); setValue({ name: '', vehicleType: 'moto', parentId: '' }) }}><input required placeholder="Nombre" value={value.name} onChange={(event) => setValue({ ...value, name: event.target.value })} /><select value={value.vehicleType} onChange={(event) => setValue({ ...value, vehicleType: event.target.value })}>{VEHICLE_TYPES.slice(0, 2).map((type) => <option key={type.id} value={type.id}>{type.label}</option>)}</select><select value={value.parentId} onChange={(event) => setValue({ ...value, parentId: event.target.value })}><option value="">Categoría principal</option>{taxonomies.filter((entry) => !entry.parentId).map((entry) => <option key={entry.id} value={entry.id}>{entry.name}</option>)}</select><button className="button">Añadir</button></form><div className="taxonomy-list">{taxonomies.map((entry) => <article key={entry.id}><div><strong>{entry.name}</strong><small>{entry.parentId ? 'Subcategoría' : `Categoría · ${entry.vehicleType}`}</small></div><button onClick={() => onToggle(entry)}>{entry.active ? 'Desactivar' : 'Activar'}</button></article>)}</div></> }

function Imports({ setMessage }) { const [file, setFile] = useState(null); const [pending, setPending] = useState(false); const [progress, setProgress] = useState(0); const [jobs, setJobs] = useState([]); useEffect(() => watchImportJobs(setJobs), []); async function submit(event) { event.preventDefault(); if (!file) return; setPending(true); try { const result = await startImport(file, setProgress); setMessage(`Archivo subido (${result.progress} %). El procesamiento continuará en segundo plano.`) } catch (error) { setMessage(error.message) } finally { setPending(false) } } return <><header className="admin-header"><div><h1>Importaciones</h1><p>Sube un archivo CSV, XLS o XLSX. Las referencias se actualizan por referencia.</p></div></header><form className="import-dropzone" onSubmit={submit}><UploadSimple size={38} /><h2>Importar catálogo</h2><p>Solo la Referencia es obligatoria. Descripción, precio, descuento y clasificación son opcionales.</p><input type="file" accept=".csv,.xls,.xlsx,text/csv,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(event) => setFile(event.target.files[0])} /><button className="button" disabled={!file || pending}>{pending ? `Subiendo ${progress} %…` : 'Subir e importar'}</button></form><div className="import-jobs">{jobs.map((job) => <article key={job.id}><strong>{job.fileName}</strong><span>{job.status}</span><small>{job.processed || 0} procesadas · {job.created || 0} nuevas · {job.updated || 0} actualizadas · {job.rejected || 0} rechazadas</small></article>)}</div></> }
