import React, { useEffect, useState } from 'react'

const content = {
  '/aviso-legal': { title: 'Aviso legal', intro: 'Información sobre el titular y las condiciones de uso de victiker.com.', sections: [['Titular del sitio', 'El titular es Víctor Pérez Tudela, con domicilio en Cl San Roque, 16, 30850 Totana, Murcia, y NIF 23333596G.'], ['Contacto', 'Puedes contactar con Victiker en el teléfono +34 673 551 065 o mediante la página de contacto.'], ['Uso del sitio', 'La información del catálogo es orientativa. La inclusión de una referencia no confirma compatibilidad, existencias ni formalización de una compraventa. Victiker confirmará esos datos al responder a la solicitud.']] },
  '/privacidad': { title: 'Política de privacidad', intro: 'Tratamiento de los datos que envías al solicitar una cita o repuestos.', sections: [['Responsable', 'El responsable del tratamiento es Víctor Pérez Tudela, con domicilio en Cl San Roque, 16, 30850 Totana, Murcia, y NIF 23333596G. Contacto: +34 673 551 065.'], ['Datos y finalidad', 'Se solicitan nombre, teléfono y, en función del formulario, información del vehículo, las piezas o el servicio solicitado. Se usan para responder y gestionar la petición.'], ['Asistente de orientación', 'Si utilizas el asistente de la portada, el texto de tu consulta se envía a OpenAI para elaborar una orientación y un embedding con el que buscar piezas del catálogo. Evita incluir nombre, teléfono u otros datos personales. La consulta sólo llega a Victiker si decides enviarla después mediante el formulario de contacto. La orientación automatizada no sustituye la revisión de Víctor.'], ['Conservación y destinatarios', 'Los datos se conservan el tiempo necesario para atender la solicitud y cumplir las obligaciones aplicables. No se venden. Los proveedores técnicos que alojan o procesan los datos sólo deben acceder a ellos para prestar el servicio contratado.'], ['Derechos', 'Puedes solicitar acceso, rectificación, supresión, oposición, limitación o portabilidad contactando con Victiker a través del teléfono indicado o del formulario de contacto.']] },
  '/cookies': { title: 'Política de cookies', intro: 'Esta interfaz no carga herramientas de analítica ni publicidad. La elección de este aviso y el modo de visualización del catálogo se guardan en el almacenamiento local del navegador, no en cookies.', sections: [['Almacenamiento técnico', 'Firebase Authentication puede guardar información de sesión en el almacenamiento del navegador para el acceso al área de administración. El catálogo no requiere iniciar sesión.'], ['Preferencias', 'Puedes rechazar el almacenamiento opcional o aceptar todas las categorías disponibles. Actualmente no hay cookies de analítica o publicidad activas. Si se incorporan, se bloquearán hasta obtener una decisión expresa.'], ['Cambiar decisión', 'Usa “Configurar cookies” en el pie de página para volver a mostrar las opciones. La selección puede eliminarse desde la configuración de almacenamiento del navegador.']] },
  '/condiciones-de-compra': { title: 'Condiciones de compra', intro: 'Las solicitudes de repuestos enviadas en la web no constituyen una compra ni un pago.', sections: [['Solicitud y confirmación', 'Victiker revisará la referencia, compatibilidad, disponibilidad, precio final y condiciones de entrega. La compra sólo se formaliza cuando se confirman expresamente esos datos y el cliente acepta la propuesta.'], ['Precio y disponibilidad', 'Los precios y existencias que puedan aparecer en el catálogo requieren confirmación antes de la compra.'], ['Desistimiento y garantías', 'En las ventas a consumidores se aplican los derechos de desistimiento, garantía legal y reclamación previstos en la normativa vigente. Las condiciones específicas de cada operación, incluidos precio total, entrega y forma de pago, se comunicarán antes de que el cliente confirme la compra.']] },
}

export function LegalPage({ path, navigate }) {
  const page = content[path] || content['/aviso-legal']
  return <><nav className="breadcrumbs" aria-label="Migas de pan"><button onClick={() => navigate('/')}>Inicio</button><span>/</span><span>{page.title}</span></nav><main className="legal-page"><p className="section-eyebrow">Información legal</p><h1>{page.title}</h1><p className="legal-intro">{page.intro}</p>{page.sections.map(([title, text]) => <section key={title}><h2>{title}</h2><p>{text}</p></section>)}</main></>
}

export function CookieNotice() {
  const [visible, setVisible] = React.useState(() => !window.localStorage.getItem('victiker-cookie-choice'))
  function choose(value) { window.localStorage.setItem('victiker-cookie-choice', value); setVisible(false) }
  useEffect(() => {
    const open = () => setVisible(true)
    window.addEventListener('victiker:cookie-settings', open)
    return () => window.removeEventListener('victiker:cookie-settings', open)
  }, [])
  if (!visible) return null
  return <aside className="cookie-notice" aria-label="Preferencias de cookies"><div><strong>Tu privacidad</strong><p>La web no carga analítica ni publicidad. Puedes rechazar el almacenamiento opcional o aceptar las categorías disponibles.</p></div><button className="cookie-secondary" onClick={() => choose('rejected')}>Rechazar opcionales</button><button className="button button--dark" onClick={() => choose('accepted')}>Aceptar todas</button></aside>
}
